<?php

return [
    '' => [
        'controller' => 'AuthController',
        'method' => 'index',
        'auth' => false,
        'methods' => ['GET'],
    ],
    'login' => [
        'controller' => 'AuthController',
        'method' => 'login',
        'auth' => false,
        'methods' => ['GET', 'POST'],
    ],
    'logout' => [
        'controller' => 'AuthController',
        'method' => 'logout',
        'auth' => true,
        'methods' => ['POST', 'GET'],
    ],
    'dashboard' => [
        'controller' => 'DashboardController',
        'method' => 'index',
        'auth' => true,
        'methods' => ['GET'],
    ],
    'ordenes' => [
        'controller' => 'OrdenesController',
        'method' => 'index',
        'auth' => true,
        'methods' => ['GET'],
    ],
    'info-cliente/editar/{slug}' => [
        'controller' => 'InfoClienteController',
        'method' => 'editar',
        'auth' => true,
        'methods' => ['GET', 'POST'],
    ],
    'ordenes/ver/{id}' => [
        'controller' => 'OrdenesController',
        'method' => 'ver',
        'auth' => true,
        'methods' => ['GET'],
    ],
    'ordenes/estado' => [
        'controller' => 'OrdenesController',
        'method' => 'cambiarEstado',
        'auth' => true,
        'methods' => ['POST'],
    ],
    'productos' => [
        'controller' => 'ProductosController',
        'method' => 'index',
        'auth' => true,
        'methods' => ['GET'],
    ],
    'productos/crear' => [
        'controller' => 'ProductosController',
        'method' => 'crear',
        'auth' => true,
        'methods' => ['GET'],
    ],
    'productos/guardar' => [
        'controller' => 'ProductosController',
        'method' => 'guardar',
        'auth' => true,
        'methods' => ['POST'],
    ],
    'productos/editar/{id}' => [
        'controller' => 'ProductosController',
        'method' => 'editar',
        'auth' => true,
        'methods' => ['GET'],
    ],
    'productos/actualizar/{id}' => [
        'controller' => 'ProductosController',
        'method' => 'actualizar',
        'auth' => true,
        'methods' => ['POST'],
    ],
    'productos/eliminar/{id}' => [
        'controller' => 'ProductosController',
        'method' => 'eliminar',
        'auth' => true,
        'methods' => ['POST'],
    ],
    'productos/eliminar_tabla_tallas/{id}' => [
        'controller' => 'ProductosController',
        'method' => 'eliminarTablaTallas',
        'auth' => true,
        'methods' => ['POST'],
    ],
    'productos/subir_imagen/{id}' => [
        'controller' => 'ProductosController',
        'method' => 'subirImagen',
        'auth' => true,
        'methods' => ['POST'],
    ],
    'productos/eliminar_imagen/{id}' => [
        'controller' => 'ProductosController',
        'method' => 'eliminarImagen',
        'auth' => true,
        'methods' => ['POST'],
    ],
    'slider' => [
        'controller' => 'SliderController',
        'method' => 'index',
        'auth' => true,
        'methods' => ['GET'],
    ],
    'slider/crear' => [
        'controller' => 'SliderController',
        'method' => 'crear',
        'auth' => true,
        'methods' => ['GET'],
    ],
    'slider/guardar' => [
        'controller' => 'SliderController',
        'method' => 'guardar',
        'auth' => true,
        'methods' => ['POST'],
    ],
    'slider/editar/{id}' => [
        'controller' => 'SliderController',
        'method' => 'editar',
        'auth' => true,
        'methods' => ['GET'],
    ],
    'slider/actualizar/{id}' => [
        'controller' => 'SliderController',
        'method' => 'actualizar',
        'auth' => true,
        'methods' => ['POST'],
    ],
    'slider/eliminar/{id}' => [
        'controller' => 'SliderController',
        'method' => 'eliminar',
        'auth' => true,
        'methods' => ['POST'],
    ],
    'categorias' => [
        'controller' => 'CategoriasController',
        'method' => 'index',
        'auth' => true,
        'methods' => ['GET'],
    ],
    'categorias/guardar' => [
        'controller' => 'CategoriasController',
        'method' => 'guardarCategoria',
        'auth' => true,
        'methods' => ['POST'],
    ],
    'categorias/eliminar' => [
        'controller' => 'CategoriasController',
        'method' => 'eliminarCategoria',
        'auth' => true,
        'methods' => ['POST'],
    ],
    'categorias/subcategorias/guardar' => [
        'controller' => 'CategoriasController',
        'method' => 'guardarSubcategoria',
        'auth' => true,
        'methods' => ['POST'],
    ],
    'categorias/subcategorias/eliminar' => [
        'controller' => 'CategoriasController',
        'method' => 'eliminarSubcategoria',
        'auth' => true,
        'methods' => ['POST'],
    ],
    'clientes' => [
        'controller' => 'ClientesController',
        'method' => 'index',
        'auth' => true,
        'methods' => ['GET'],
    ],
    'clientes/ver/{id}' => [
        'controller' => 'ClientesController',
        'method' => 'ver',
        'auth' => true,
        'methods' => ['GET'],
    ],
    'usuarios' => [
        'controller' => 'UsuariosController',
        'method' => 'index',
        'auth' => true,
        'methods' => ['GET'],
    ],
    'usuarios/crear' => [
        'controller' => 'UsuariosController',
        'method' => 'crear',
        'auth' => true,
        'methods' => ['GET'],
    ],
    'usuarios/guardar' => [
        'controller' => 'UsuariosController',
        'method' => 'guardar',
        'auth' => true,
        'methods' => ['POST'],
    ],
    'usuarios/editar/{id}' => [
        'controller' => 'UsuariosController',
        'method' => 'editar',
        'auth' => true,
        'methods' => ['GET'],
    ],
    'usuarios/actualizar/{id}' => [
        'controller' => 'UsuariosController',
        'method' => 'actualizar',
        'auth' => true,
        'methods' => ['POST'],
    ],
    'usuarios/eliminar/{id}' => [
        'controller' => 'UsuariosController',
        'method' => 'eliminar',
        'auth' => true,
        'methods' => ['POST'],
    ],
];
