<?php

return [
    '' => ['HomeController', 'index'],
    'buscar' => ['SearchController', 'index'],
    'search/ajax' => ['SearchController', 'ajax'],
    'productos' => ['ProductosController', 'index'],
    'productos/detalle' => ['ProductosController', 'detalle'],
    'detalle_producto' => ['ProductosController', 'detalle'],
    'ofertas' => ['ProductosController', 'ofertas'],
    'checkout' => ['CheckoutController', 'index'],
    'carrito' => ['CarritoController', 'index'],
    'carrito/agregar' => ['CarritoController', 'agregar'],
    'carrito/eliminar' => ['CarritoController', 'eliminar'],
    'carrito/actualizar' => ['CarritoController', 'actualizar'],
    'carrito/vaciar' => ['CarritoController', 'vaciar'],
    'carrito_compras' => ['CarritoController', 'index'],
    'blog' => ['BlogController', 'index'],
    'blog/ver' => ['BlogController', 'ver'],
    'ver_blog' => ['BlogController', 'ver'],
    'mi-cuenta' => ['CuentaController', 'index'],
    'mi_cuenta' => ['CuentaController', 'index'],
    'ver-orden' => ['CuentaController', 'verOrden'],
    'ver_orden' => ['CuentaController', 'verOrden'],
    'para-el-cliente' => ['ClienteController', 'index'],
    'para_el_cliente' => ['ClienteController', 'index'],
    'libro-de-reclamaciones' => ['ClienteController', 'libro'],
    'libro_de_reclamaciones' => ['ClienteController', 'libro'],
    'admin' => ['AdminController', 'login'],
    'admin/login' => ['AdminController', 'login'],
    'admin/dashboard' => ['AdminController', 'dashboard'],
    'admin/productos' => ['AdminController', 'productos'],
];
